kind: Secret
ansible_user: ENC[AES256_GCM,data:VOliifSc2KA=,iv:iY9+9NoESTVgvF12tAoJdC4BuB1FTubNkVqu5bubwmY=,tag:TxsGN/lf7F9T9I2DDXs0wg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:luPNbTQ3,iv:/ZJjH8uyp5y8gnB2e/VLKzXH0GT0kfAfdoTHbJ0SjXQ=,tag:k1PjFInBPdTdDKb+JmLJhQ==,type:str]
mail: ENC[AES256_GCM,data:hyJjsOkYfThe5Rdkuf/ywNc=,iv:Rp1FmaNVnP48bypn+X/jpZpjBTKnLjjwbHAZfpVYzQc=,tag:jSNn+mS+yzr0X8PtyRnE7Q==,type:str]
plik_url: ENC[AES256_GCM,data:+15og91o+4v1D8nlar4pazlXXEm1jfug,iv:FDPfI/VG91B5b2Uzsr7LjYeLRgUEbs52aF14EA0wdw8=,tag:1CXZdZsf6YkMSAlfYnAoAw==,type:str]
plik_token: ENC[AES256_GCM,data:Tln/FR6fOcy2RKiFO3regUFjLYiAB7hWJSPXb3IqyjSclW3O,iv:cpGK7v+wqyfmF7S5JyhmR/yteBELkOQUSZh8CHmTX/s=,tag:c/TUSqXtgY2jgvA4OHhVfw==,type:str]
k3s_token: ENC[AES256_GCM,data:0x1keqdICnp9Z57NltsV8SPJZgXhQVUiknQbUHHj5cU3J2aRLbAWtXf5dmyMC2KPEMM9Hu3cg8Ik4fFTxChOdHusmFDzuHbm/OgTa8rQaeXExeGF1Cjt3jDBQ6BUlu+ITQyHw8ljmhzG6g1O,iv:oiMZfLQfdLSYZzrrqFo7Lv6+lIobPi3kMK43xtIQ1vc=,tag:bLevHtviOQLcRwIZkY0fhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweTFmcFRrd0g2Sk8yZXZC
            ZCs5WGF5cFVFbXErK1hrSFBZZkJOa1hCbUE0CjQzdGVrMHFvQnJ6Vk1kUXA3cXNM
            T0hEZUZJSndFdTVHMWlMY2hjRHJ3SEkKLS0tIGV5dk13QTVqcTZrNlB1cWhzUWJH
            TXkvOWlMc3pic1pkcDZsNlNScThVZ0kKlAJBUs92ywZft95AZO7Xmf97b7n5uEje
            igsPmvJy9gc+Qj5o3FM1MMkCZQAjXYEXgnGlKuyTqQNGPGskg/UTEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T20:17:24Z"
    mac: ENC[AES256_GCM,data:vRdGOQoL1Y7mXozxV71Y8oM2EgZkXjOB1CiGBm5LVonNfApWaueFIWlyh1s+hC6e85Qff1ZXuMcQ6uU7XUEfx+SNa5Oeg6P8aYwzzM3YodOI3Jzb/DiDsCApg/51vEMfc/zkoH7qSTetdVy54o0KT1+Hg/NPj5+qv1BtFh/uXhw=,iv:Qm3+Khc1ML8NDimmjNsWPHZzOwp+f41jG5KCpIXlH7I=,tag:3hZJmzJZNNMqzvMATWiDeQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
