---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: default
data:
  K3S_MASTER_VIP: 192.168.1.9
  VIP_INTERFACE: eth0
  LB_TRAEFIK_ADDRESS: 192.168.1.200
  LB_OPENLDAP_ADDRESS: 192.168.1.201
  LB_PIHOLE_ADDRESS: 192.168.1.202
  LB_SMTP_RELAY_ADDRESS: 192.168.1.203
  LB_MQTT_ADDRESS: 192.168.1.204
  LB_OLLAMA_ADDRESS: 192.168.1.205
  LB_GO2RTC_ADDRESS: 192.168.1.206
  LB_WHISPER_ADDRESS: 192.168.1.207
  LB_PIPER_ADDRESS: 192.168.1.208
  LB_OPENWAKEWORD_ADDRESS: 192.168.1.209
  ZIGBEE_COORDINATOR_ADDRESS: 192.168.1.30
  NAS_ADDRESS: 192.168.1.50
  TZ: "Europe/Paris"
