apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:nkOJsrTj0md6rk6bjbsdnMFFocK4yHpdBAU=,iv:oUIUOY+13XoOABoFlhHA2R51GwA4fZolwEsnYqtfHbI=,tag:XwMoh6aFvEVX/NL3HFPNpg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:n7PIIBKN5w14ooY=,iv:IC5CG81j4rSrkHBsOQmtNZA6RXoeIQX9dUbIF2BpLZo=,tag:3L13vtJdkQtQh8Z0ONT3EQ==,type:str]
    SECRET_DYNAMIC_DOMAIN: ENC[AES256_GCM,data:BR4jn4IDKkjR/F0sRzw=,iv:vitvtXFHumlK6O6WvJOQjlP311D8jaUrj74CIy0uP4Q=,tag:kYN2+K6fMl+UgJH00+79Qw==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:Sn7vbJAYnrTwxYDtO57CKA==,iv:kjHAL6uO40S50SKUE6i6pmvK/m4l3eQxj4Z5rA4+bEo=,tag:NWA4o6SI636L6qS5HS+kFA==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:xB+SAmqvotjReygh6cvcwBc=,iv:PluWrcTslNkNeV6nQdgJ77ELCh9TMIwDOdbIb8bFGbQ=,tag:nac5sjzkqDVxjdpwATEBlQ==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:+5cLBx/WOkJG0uM8dqgXaOUFwXE=,iv:i88RBl8B/4vLbcdVaFoSfRXSWRJNp7EDueQgcz7wOMM=,tag:1Fa5QmbU4sFHq53FwPibkQ==,type:str]
    SECRET_JOPLIN_NOREPLY_EMAIL: ENC[AES256_GCM,data:Vz1FkDrvuxlR/jT/L63AN7gLDyQS/D1J,iv:TtZ4lkPJoVO+947CvV8rchemOyE3l2TNw1RGWk11USI=,tag:IvChPAVqQYeYyS0V3rf3iA==,type:str]
    SECRET_MEALIE_FROM_EMAIL: ENC[AES256_GCM,data:T3b+CKHXvRsPUy0YJOA9BnFct7V6jybB,iv:AgkLnD9tIHMr8X1cUoFkr295OR1TQ5LKSZ+LM7ouXZI=,tag:p0etHzAX5cdZGWC+/LRhGA==,type:str]
    SECRET_LDAP_ADMIN_BIND_DN: ENC[AES256_GCM,data:I5SoWWa0DzdtXsfppbWQz5qTNd0LmLJuRSz70rc6oXwgcHem6uc=,iv:uXzsa1aXgs2BN3rKdfKXTs3b/501tys2Dc9p0GLwrJ0=,tag:swTruhFkexjzIzBmzsmLVg==,type:str]
    SECRET_LDAP_ADMIN_QUERY_PASSWORD: ENC[AES256_GCM,data:j0JXtFW4u/EjAtClSGrUSW3/qrQyRX/24A==,iv:ThjyowkezhAoxg59DxJSQL2WzgfJQncnCVjCA7MEM3M=,tag:8NdbaqW7S4GxBmhUSyfhGA==,type:str]
    SECRET_AUTHELIA_SENDER_EMAIL: ENC[AES256_GCM,data:r8UGyF5/v161oywMNlRxXIPg7rdJO371zAML4DOi6sikzhZMEinCnTDZg7egN/RxauODlFtLl7/Yuok=,iv:zbshd8jNgR70MDHPt71fpJLiJBIq1HvvLu+WjNfNeNc=,tag:2uckw2TlCl/qkLBpfuMWiA==,type:str]
    SECRET_IMMICH_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:b0+1gmclufS3hlYGyH3VzQWATIbPobLOZ8cZg1HALpEXDr5njLOJr93QLChHO5um3Zam92XwMEJlmpTzY8Qk2Oyn9OvCX42+rnSzgQ9SqHBjtWrr6ui1dxJ/SRmgouS2ZqL395/o3P0in3L7oCpAZ2n4T2zgyH3udIJmdlUpVkU=,iv:CoYLUK0n2Y4TZ1EcQptjK8vKzPX2xBGdS5ph1LRswwU=,tag:OK0VNkGIqc3zHSIC03uYkg==,type:str]
    SECRET_WEAVE_GITOPS_ADMIN_PASSWORD: ENC[AES256_GCM,data:7T8ahSUkuoO67rNQfaLi3LEnDQqR2DBmVJV8HHc8Aua91XM6SFw6m3ZIQepk96BjPZ0YTsudRFztawDx,iv:R7ep0GtealODtLnCJqxX5b0Sa6KwEwKHh/fhswQEbdw=,tag:qJ1HUJiv6MdMoKuqvMucBw==,type:str]
    SECRET_CAMERA_PASSWORD: ENC[AES256_GCM,data:bYNMNpaS+FxSwZhD6X0zgl5H,iv:Bhp3acgtgnP1KuReI6UP871QOIiMBqqvBKqH+h5UnAw=,tag:z4BQPOM8ZRpC57LlmwTN7Q==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTjFBQWh4SXFPeGwwNklM
            Y3N4OXlxM2ZFV0pyckVDb21DUU5jdWdKcGpBCjlDd0ZQK1dQZG1WZnJNZUdSNDl5
            OElmNC9HUjhZdEZoSUJZcVhTTGRiQk0KLS0tIEs4Q3FvcEVlYlRHMjFxb0JIeWFI
            d1k5WTZla0hGMFJpa253WXdVVVNSTUUKtsCalJBZZPv5Dd1/rFoH7NPvpoPOo7rC
            xr2tBrxca0bJu4gjktVAyIXBxvCpWvUiOZtBSSRzUsWqY2pWxKfhSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T13:54:19Z"
    mac: ENC[AES256_GCM,data:o8msAikQcxhjDyEV7kVV/4t5roD9cTgfpx2xRqqywFhCZxoL8GqSSDk1e6S1nz1OPt0bDXwBcDSmkh/fo5+7I1hjRjX/gywWMmN+XRdAhHPdHl5tUPlacOZYchyWYwkMrgknRqH4daxOcdDnbWHmy79R8FWbk2Q+hZ8madKl+JI=,iv:2oX4KPyLThEwiGqgLIsw8phm0kxKzUQWY5cwNpkh/8M=,tag:WcGP4YBVvyPrMFmq5XbNwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
