---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - kube-system
  - kubernetes-dashboard
  - monitoring
  - networking
  - node-feature-discovery
  - reloader
  - storage
#  - system-upgrade
