---
metrics:
  serviceMonitor:
    enabled: true
persistence:
  defaultClass: false
  defaultClassReplicaCount: "2"
defaultSettings:
  defaultReplicaCount: "2"
  defaultDataPath: "/storage"
  backupTarget: "nfs://{{NAS_ADDRESS}}:/volume1/k3s/longhorn_backup"
  replicaSoftAntiAffinity: true
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
