---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../config
  - ollama.yaml
replacements:
  - source:
      kind: ConfigMap
      name: cluster-settings
      namespace: default
      fieldPath: data.LB_OLLAMA_ADDRESS
    targets:
      - select:
          kind: Service
          name: ollama
          namespace: home-automation
        fieldPaths:
          - metadata.annotations.[metallb.io/loadBalancerIPs]
