---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - kustomization.yaml
  - role.yaml
  - serviceaccount.yaml
